"""add_filename_to_documents

Revision ID: 5b97c84b829e
Revises: 004a81c90dfc
Create Date: 2025-09-04 03:51:55.949346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b97c84b829e'
down_revision: Union[str, Sequence[str], None] = '004a81c90dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
